// Package storage provides filesystem-backed implementations of
// the scm/domain.DiffStore port. Today there is one: FileStore,
// which persists the diff under the OS cache dir so the CLI does
// not have to re-fetch on every category pass.
//
// Adapters live in their own package (rather than next to the
// use case) so the use case stays free of filesystem imports and
// the adapter can be swapped for an in-memory or remote one
// without touching the bounded context.
package storage

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	scmdomain "github.com/LucasNav6/code-review-cli/internal/scm/domain"
)

const diffFilename = "review.diff"

// FileStore is a scm/domain.DiffStore backed by a single file on
// the local filesystem. The path is resolved at construction time
// (see NewFileStore) so callers do not have to thread a path
// through every method call.
type FileStore struct {
	path string
}

// NewFileStore returns a FileStore pointing at the standard cache
// location (os.UserCacheDir + "/code-review/review.diff"). If the
// user cache dir cannot be resolved, the constructor falls back to
// os.TempDir so the CLI still works on minimal environments (CI,
// stripped containers, etc.).
//
// The constructor does NOT create the directory — Save does. We
// keep creation close to the write so a CLI that never Saves (e.g.
// a dry-run mode) leaves no artefacts behind.
func NewFileStore() FileStore {
	dir, err := os.UserCacheDir()
	if err != nil || dir == "" {
		dir = os.TempDir()
	}
	return FileStore{
		path: filepath.Join(dir, "code-review", diffFilename),
	}
}

// Path returns the absolute path the store reads from / writes to.
// Exposed so the composition root can mention it in user-facing
// logs ("diff saved to /tmp/...").
func (s FileStore) Path() string {
	return s.path
}

// Save writes the diff body to the store's path. The directory is
// created with 0o755 permissions; the file with 0o644. Errors are
// wrapped so the use case can route them through its own logging
// facade without losing the underlying cause.
//
// Save is intentionally NOT atomic (no temp + rename): the diff is
// regenerated by re-fetching from the SCM if it is corrupt, so a
// partial write does not lose any unrecoverable state.
func (s FileStore) Save(d scmdomain.Diff) error {
	if err := os.MkdirAll(filepath.Dir(s.path), 0o755); err != nil {
		return fmt.Errorf("create cache dir: %w", err)
	}
	if err := os.WriteFile(s.path, d.Body, 0o644); err != nil {
		return fmt.Errorf("write diff: %w", err)
	}
	return nil
}

// Load reads the previously-saved diff. Returns scmdomain.ErrNoStoredDiff
// when nothing has been saved yet. Returns a wrapped fs error
// when the file exists but is unreadable (permission change,
// corruption, etc.) — the use case can decide how to surface it.
//
// An empty file is treated as "nothing saved" (matches the old
// behaviour of internal/review/load.go so the migration does not
// change semantics).
func (s FileStore) Load() (scmdomain.Diff, error) {
	data, err := os.ReadFile(s.path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return scmdomain.Diff{}, scmdomain.ErrNoStoredDiff
		}
		return scmdomain.Diff{}, fmt.Errorf("read %s: %w", s.path, err)
	}
	if len(data) == 0 {
		return scmdomain.Diff{}, scmdomain.ErrNoStoredDiff
	}
	return scmdomain.Diff{Body: data}, nil
}

// Compile-time check: FileStore satisfies the DiffStore port.
var _ scmdomain.DiffStore = FileStore{}